"""OMP native export driver.

Writes the parity-gated OMP package layout under ``<export_root>/.omp/z-harness``.
This is intentionally separate from the legacy pi exporter: no pi assets, prompt
rewrites, or line-rewrite helpers are imported or called here.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from runtime.drivers._export_utils import ExportResult, enumerate_sources, export_resume_runtime_scripts

_PACKAGE_DIR = ".omp/z-harness"
_CONFIG_PATH = ".omp/config.yml"


def _current_fidelity() -> str:
    """Read OMP export fidelity from the parity gate.

    Deferred import avoids a circular dependency (runtime → cli adapters).
    The gate is the single source of truth for all three OMP fidelity surfaces.
    """
    try:
        from z_harness_cli.adapters.omp_parity_gate import omp_export_fidelity
        return omp_export_fidelity()
    except ImportError:
        # Fallback: if the CLI layer is not importable (isolated runtime test
        # environment), remain conservative.
        return "partial"


_CONFIG_YML = """# z-harness OMP export discovery guidance.
# Point OMP_PLUGIN_ROOT at the sibling .omp/z-harness package root.
# Keep project AGENTS.md autoload disabled so OMP does not ingest unrelated root context.
skills:
  enableAgentsProject: false
"""


def _yaml_scalar(value: object) -> str:
    """Return a double-quoted YAML scalar for small generated metadata files."""
    text = str(value)
    return json.dumps(text, ensure_ascii=False)


def _frontmatter_lines(frontmatter: dict[str, str]) -> list[str]:
    lines: list[str] = []
    for key in sorted(frontmatter):
        value = frontmatter[key]
        if value:
            lines.append(f"source_{key}: {_yaml_scalar(value)}\n")
    return lines


def _render_markdown_resource(entry: dict[str, Any], *, kind: str, heading: str) -> str:
    source_path = entry.get("source_path")
    source = source_path.as_posix() if isinstance(source_path, Path) else str(source_path or "")
    body = str(entry.get("body", "")).lstrip("\n")
    lines = [
        "---\n",
        f"id: {_yaml_scalar(entry['id'])}\n",
        f"type: {_yaml_scalar(kind)}\n",
        f"source: {_yaml_scalar(source)}\n",
        *_frontmatter_lines(entry.get("frontmatter", {})),
        "---\n",
        "\n",
        f"# {heading}: {entry['id']}\n",
        "\n",
    ]
    lines.append(body)
    if body and not body.endswith("\n"):
        lines.append("\n")
    return "".join(lines)


def _render_manifest(repo_root: Path, sources: dict[str, list[dict[str, Any]]], *, fidelity: str) -> str:
    version = _resolve_version(repo_root)
    lines = [
        "# Generated by z-harness export --host omp.\n",
        "name: z-harness\n",
        "host: omp\n",
        f"fidelity: {fidelity}\n",
    ]
    if version:
        lines.append(f"version: {_yaml_scalar(version)}\n")
    lines.extend(
        [
            "discovery:\n",
            "  env: OMP_PLUGIN_ROOT\n",
            "  package_root: .omp/z-harness\n",
            "  config: ../config.yml\n",
            "resources:\n",
            f"  skills: {len(sources['skills'])}\n",
            f"  rules: {len(_prompt_entries(sources))}\n",
            f"  prompts: {len(_prompt_entries(sources))}\n",
            f"  agents: {len(sources['agents'])}\n",
            "paths:\n",
            "  skills: skills/\n",
            "  rules: rules/\n",
            "  prompts: prompts/\n",
            "  agents: agents/\n",
            "config_guidance:\n",
            "  skills.enableAgentsProject: false\n",
        ]
    )
    return "".join(lines)


def _resolve_version(repo_root: Path) -> str | None:
    manifest = repo_root / ".claude-plugin" / "plugin.json"
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    value = data.get("version")
    return str(value) if value else None


def _prompt_entries(sources: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    """Return entries that should be discoverable as OMP prompts/rules.

    ``commands/`` is retained for backward compatibility, but current z-harness
    command sources live as skills, so skills also receive prompt/rule wrappers.
    """
    by_id: dict[str, dict[str, Any]] = {}
    for entry in sources.get("commands", []):
        by_id[entry["id"]] = entry
    for entry in sources.get("skills", []):
        by_id.setdefault(entry["id"], entry)
    return [by_id[key] for key in sorted(by_id)]


def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path.resolve()


def _remove_owned_path(path: Path) -> None:
    """Remove one generated OMP export path without touching its siblings."""
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.exists():
        shutil.rmtree(path)


def export(
    repo_root: Path,
    export_root: Path,
    *,
    options: dict[str, Any] | None = None,
) -> ExportResult:
    """Export z-harness resources to the OMP-native package layout.

    The export root receives ``.omp/config.yml`` guidance plus the package root
    ``.omp/z-harness`` containing manifest, skills, rules, prompts, and agents.
    Fidelity remains ``partial`` until the final OMP parity gate.
    """
    del options
    repo_root = Path(repo_root).resolve()
    export_root = Path(export_root).resolve()
    package_root = export_root / _PACKAGE_DIR

    sources = enumerate_sources(repo_root)
    emitted: list[Path] = []
    fidelity = _current_fidelity()

    _remove_owned_path(package_root)
    _remove_owned_path(export_root / _CONFIG_PATH)

    emitted.append(_write(export_root / _CONFIG_PATH, _CONFIG_YML))
    emitted.append(_write(package_root / "manifest.yml", _render_manifest(repo_root, sources, fidelity=fidelity)))

    for entry in sources["skills"]:
        source_text = entry["source_path"].read_text(encoding="utf-8")
        emitted.append(_write(package_root / "skills" / entry["id"] / "SKILL.md", source_text))

    for entry in _prompt_entries(sources):
        prompt_text = _render_markdown_resource(entry, kind="prompt", heading="Prompt")
        rule_text = _render_markdown_resource(entry, kind="rule", heading="Rule")
        emitted.append(_write(package_root / "prompts" / f"{entry['id']}.md", prompt_text))
        emitted.append(_write(package_root / "rules" / f"{entry['id']}.md", rule_text))

    for entry in sources["agents"]:
        agent_text = _render_markdown_resource(entry, kind="agent", heading="Agent")
        emitted.append(_write(package_root / "agents" / f"{entry['id']}.md", agent_text))

    emitted.extend(export_resume_runtime_scripts(repo_root, package_root))

    return ExportResult(
        dest=package_root.resolve(),
        files=emitted,
        fidelity=fidelity,
        warnings=[],
    )
